import { UIMessage } from "../types.slint";
import { LineEdit, Button } from "std-widgets.slint";

export component ChatView {
    in property <string> chat_name;
    in property <[UIMessage]> messages;
    property <string> message;
    callback send_message(message: string);

    width: 100%;

    VerticalLayout {
        Rectangle {
            background: #10101e;
            max-height: 36px;

            HorizontalLayout {
                padding: 8px;

                Text {
                    text: chat_name;
                    font-size: 24px;
                }
            }
        }

        VerticalLayout {
            alignment: start;

            for i in 12: HorizontalLayout {
                padding: 8px;
                property <UIMessage> message: messages[(messages.length - 12) + i];

                Text {
                    text: message.content.character-count != 0 ? "\{message.author}: \{message.content}" : "";
                    font-size: 16px;
                }
            }
        }

        Rectangle {
            background: #10101e;
            max-height: 36px;

            HorizontalLayout {
                padding: 8px;
                spacing: 8px;

                LineEdit {
                    horizontal-stretch: 1;
                    font-size: 14px;
                    placeholder-text: "Message \{chat_name}...";
                    text <=> message;

                    accepted(text) => {
                        send_message(message);
                        message = "";
                    }
                }

                Button {
                    text: "Send";

                    clicked => {
                        send_message(message);
                        message = "";
                    }
                }
            }
        }
    }
}
