import { MenuState, UIMessage } from "../types.slint";
import { Button, LineEdit } from "std-widgets.slint";

export component HostView {
    in-out property <MenuState> menu_state;
    property <string> user;
    property <string> room;
    callback host(room: string, user: string);

    function host_local() {
        menu_state = MenuState.Loading;

        host(room, user);
    }

    VerticalLayout {
        spacing: 32px;

        Text {
            horizontal-alignment: center;
            text: "Host";
            font-size: 36px;
            color: white;
        }

        VerticalLayout {
            spacing: 8px;
            alignment: start;

            LineEdit {
                placeholder-text: "Username";
                text <=> user;

                accepted(text) => { roombox.focus() }
            }

            roombox := LineEdit {
                placeholder-text: "Room Name";
                text <=> room;

                accepted(text) => { host_local() }
            }

            Button {
                text: "Host";

                clicked => { host_local() };
            }

            Button {
                text: "Back";

                clicked => { menu_state = MenuState.Home };
            }
        }
    }
}
